#' @importFrom yaml read_yaml
#' @importFrom furrr future_imap
#' @importFrom purrr imap
#' @importFrom progressr progressor
#' @importFrom rlang as_function
#' @importFrom rlang global_env
#' @importFrom purrr pluck
#' @importFrom purrr imap
#' @importFrom purrr compact
#' @importFrom cli cli_abort 
#' @importFrom stringr str_starts
#' @importFrom stringr fixed
#' @importFrom rlang abort
#' @importFrom glue glue
#' @importFrom cli cli_abort
#' @importFrom rlang current_env
#' @importFrom rlang has_name
#' @importFrom rlang abort
#' @importFrom glue glue
#' @importFrom cli cli_inform
#' @importFrom purrr iwalk
#' @importFrom ggplot2 ggsave
#' @importFrom cli cli_warn
#' @importFrom rlang env_parent
#' @importFrom rlang global_env
#' @importFrom rlang env
#' @importFrom rlang is_empty
#' @importFrom purrr map 
#' @importFrom purrr list_assign
#' @importFrom callr r
#' @importFrom rlang current_env
#' @importFrom rlang ensym
#' @importFrom rlang as_name
#' @importFrom rlang env_poke
#' @importFrom rlang abort
#' @importFrom glue glue
NULL